name: java c
on:                                                  
  push:
    branches: [ '**' ]

jobs:
  java-runner:                                             
    runs-on: ubuntu-latest                           

    steps:                                           
      - name: Checkout code                          
        uses: actions/checkout@v4                    
      
      - name: Compile Java                            
        run: javac src/Main.java

      - name: Run executable                          
        run: java -cp src Main
